import os
from flask import current_app
from flask_mail import Message

def send_report_email(patient_email, patient_name, doctor_name,
                      consultation_id, pdf_filename, patient_token):
    """Send PDF report to patient email after approval."""
    try:
        mail = current_app.extensions['mail']
        output_folder = current_app.config["OUTPUT_FOLDER"]
        pdf_path      = os.path.join(output_folder, pdf_filename)

        if not os.path.exists(pdf_path):
            print(f"PDF not found: {pdf_path}")
            return False

        patient_url = f"http://127.0.0.1:5000/patient/{patient_token}"

        msg = Message(
            subject=f"Your MediNote AI Consultation Report — {patient_name}",
            recipients=[patient_email]
        )
        msg.html = f"""
        <div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto">
          <div style="background:#1a56db;padding:24px;border-radius:12px 12px 0 0;text-align:center">
            <h2 style="color:#fff;margin:0">🏥 MediNote AI</h2>
            <p style="color:rgba(255,255,255,.8);margin:6px 0 0">Clinical Documentation System</p>
          </div>
          <div style="background:#fff;padding:28px;border:1px solid #e5e7eb;border-top:none">
            <p style="font-size:15px;color:#374151">Dear <b>{patient_name}</b>,</p>
            <p style="color:#6b7280;line-height:1.6">
              Your consultation report from
              <b>Dr. {doctor_name}</b> has been reviewed, approved, and is ready.
              Please find your PDF report attached to this email.
            </p>
            <div style="background:#f0f4ff;border-radius:10px;padding:16px;margin:20px 0;text-align:center">
              <p style="margin:0 0 12px;color:#374151;font-weight:600">
                View your report online
              </p>
              <a href="{patient_url}"
                 style="background:#1a56db;color:#fff;padding:10px 28px;
                        border-radius:8px;text-decoration:none;font-weight:600">
                Open My Report &amp; Prescription
              </a>
            </div>
            <p style="font-size:12px;color:#9ca3af;margin-top:20px;border-top:1px solid #f3f4f6;padding-top:16px">
              This report was generated by MediNote AI at
              Hindustan Institute of Technology and Science.
              Report ID: MN-{consultation_id:04d}
            </p>
          </div>
        </div>
        """

        # Attach PDF
        with open(pdf_path, "rb") as f:
            msg.attach(
                filename=f"MediNote_Report_{patient_name.replace(' ','_')}.pdf",
                content_type="application/pdf",
                data=f.read()
            )

        mail.send(msg)
        print(f"Email sent to {patient_email} ✅")
        return True

    except Exception as e:
        print(f"Email failed: {e}")
        return False